# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

[plugins.async]
github = "mafredri/zsh-async"

[plugins.pure]
github = "sindresorhus/pure"

[plugins.sudo]
github = "hcgraf/zsh-sudo"

[plugins.extract]
github = "thetic/extract"

[plugins.autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.completions]
github = "zsh-users/zsh-completions"

[plugins.fzf-hist]
github = "joshskidmore/zsh-fzf-history-search"

[plugins.gitaliases]
github = "davidde/git"
